#!/bin/bash

# make_page - A script to produce an HTML file

cat <<- _EOF_
	<HTML>
	<HEAD>
		<TITLE>
		This is my page
		</TITLE>
	</HEAD>

	<BODY>
		There are many like it, but this one is mine.
	</BODY>
	</HTML>
_EOF_
